### PR TITLE
add java-objc-bridge patch

### LINKED ISSUE #1: Also patch java-objc-bridge
One thing that I noticed is that the TTS engine in Minecraft uses `ca.weblite.java-objc-bridge`, which in version 1.1 supports macOS arm64 but the version Minecraft uses is 1.0.0.

So I was wondering if you could also patch this library along with LWJGL, since without patching the TTS engine fails to initialize and throws an error.

[Maven](https://mvnrepository.com/artifact/ca.weblite/java-objc-bridge/1.1)
[java-objc-bridge-1.1.tar.gz](https://github.com/Dreamail/M1MC/files/8189952/java-objc-bridge-1.1.tar.gz)

### PR DESCRIPTION
**Pull request by ryanccn**
This PR closes #1.

### CODE REVIEW

**Comment by ryanccn** [comment]
By the way, where do you download the `dylib`s?

Do you unpack them from the `*-native.jar`s in the LWJGL customized build download or something else?

It looks like there's also dylibs [here](https://www.lwjgl.org/browse/stable/macosx/arm64) for download.
﻿

**Comment by ryanccn** [comment]
@Dreamail

**Comment by ryanccn** [comment]
Here's a sample - it runs 1.18.1 with **no errors whatsoever** on macOS arm64!

[M1MC-java-objc-bridge.zip](https://github.com/Dreamail/M1MC/files/8190232/M1MC-java-objc-bridge.zip)

**Comment by ryanccn** [comment]
lol you still haven't released it @Dreamail

**Comment by Dreamail** [comment]
Oh I do it right now.

**Comment by Dreamail** [comment]
No time left. I'm sorry.

**Comment by Dreamail** [comment]
@ryanccn released

**Comment by ryanccn** [comment]
OK! thanks

**Pull request merged**
